version: 1

merge:
  trigger:
    labels: ["Merge"]
    comment_substrings: ["==MERGE_WHEN_READY=="]
  ignore:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: merge
  delete_after_merge: true
  allow_merge_with_no_checks: true

update:
  trigger:
    labels: ["WIP", "Update Me"]
