
version: 1

merge:
  trigger:
    labels: ["Merge"]
  ignore:
    labels: ["DO_NOT_MERGE", "SKIP_ALL"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  branch_method:
    develop: squash
    main: squash
  options:
    squash:
      title: "pull_request_title"
      body: "summarize_commits"
      message_delimiter: ==COMMIT_MSG==
  delete_after_merge: true
  allow_merge_with_no_checks: true

